# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Dumper-HTML
version:      v0.0.2
version_from: lib/Data/Dumper/HTML.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Text::InHTML:                  0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
